version: '3'

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 192.30.0.0/24

services:

  openvas:
    image: mikesplain/openvas
    ports:
      - '443:443'
    volumes:
      - './data:/var/lib/openvas/mgr'
    networks:
      mynetwork:
        ipv4_address: 192.30.0.4

  db:
    image: bddimage:latest
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: keycekeyce

    networks:
      mynetwork:
        ipv4_address: 192.30.0.2

  wordpress:
    depends_on:
      - db
    links:
      - db
    image: wordpress:latest
    ports:
      - '8083:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: keycekeyce
      WORDPRESS_DB_NAME: wordpress
    networks:
      mynetwork:
        ipv4_address: 192.30.0.3
    volumes:
      - ./wp-content:/var/www/html/wp-content

  openvas_scan:
    image: python:3.9
    command: python openvas_scan.py

volumes:
  db_data: {}